### PR TITLE
Do not stop browser on upgrade

### PR DESCRIPTION
**Pull request by opoplawski**
We use an automatic update process that then alerts users to the need to restart their browser.  It is not helpful to have the browser immediately terminated out from under them.

### CODE REVIEW

**Comment by Hibbiki** [comment]
The browser will restart during update only if it is being installed as system-wide installation. In such case, browser files are in `%programfiles%` and restarting browser __will not__ update current `chrome.exe` file due to lack of permissions for current user to that directory. Official Google solution is to use `Google Update` service to elevate during update request however that code is private and inert in non-Chrome branded builds. As such, your choice is to have browser restart during install or it never be updated.

If you have came up with your own solution to move `chrome.exe` file, then you should build your own Chromium without applying patch `0001`, or you can consider switching from informing user to restart browser to informing user that an update which will close browser will take place.

**Comment by Hibbiki** [comment]
Some background on how update process works for system-level installs:
- It extracts current version into new directory in `%programfiles%\Chromium\Application` named after version being installed
- It extracts `chrome_proxy.exe` and `chrome.exe` to the `%programfiles%\Chromium\Application`
- If existing files of these names already exist it will replace them, unless the files are locked due to browser being already open, in which case `new_` prefix is appended to them.
- (Chrome-branded builds only) Informs `Google Update` service about necessity to restart browser, browser displays prompt to user in dot-menu
- (Chrome-branded builds only) `Google Update` starts monitoring for when browser exists and when it does so, it renames files with prefix `new_` to their original names and removing previous version directory, hence completing update process. Opening browser will now run a new version.

On Chromium builds, last 2 steps do not happen and if browser was already running, `new_chrome.exe` is never renamed back to `chrome.exe` under any circumstances unless manual intervention happen. In order to provide general-use builds to users I have decided to patch installer to forcefully close browser when it detects it is updating system-level installation, so that files can be updated automatically. I understand that this is not desirable outcome, however there is simply no alternative present that I could make use of that I know of.

**Comment by opoplawski** [comment]
Thank you very much for the detailed explanation of the update process.  Since we have very few chromium users and they are admin users I think just informing them of the need to update will be sufficient.  It's unfortunate that the old .exe's are not renamed out of the way, but perhaps that is not allowed in Windows.

**Comment by underdoq** [comment]
Sorry, is there a way to auto update client using your releases ?

**Comment by ioc2e3** [comment]
That ...

Hopefully here ( https://github.com/Hibbiki/chromium-win64/releases ) ...

provides a portable version for Windows ...

.

**Pull request closed without merging**
